# @package _global_
defaults:
  - cc359/base_recon
  - override /representation: identity
  - override /reconstruction: default_variational_diff
  - override /sample_logger: with_target

sampler_logger:
  volume_stats_period: 10
  volume_stats__wandb_take_mean_slice_period: 10
  
reconstruction:
  variational:
    fitting:
      optimizer:
        lr: 2.0
        iterations: 300
        clip_grad_max_norm: 1.0
    regularization:
      reg_strength: 0.01